Feature/sign 6807
SignPath/github-actions pull request #11
Opened 2024-03-08 11:53 UTC by volbobvol

- Added new action parameter - "github-extended-verification-token"
- Updated documentation to cover all possible parameters

2024-03-08 13:25 UTC, paulsavoie approved these changes

2024-03-08 13:25 UTC, paulsavoie commented on README.md
> +* `connector-url` (optional): The URL of the SignPath connector. Defaults to `https://api.signpath.io`
This is wrong, should be `https://githubactions.connectors.signpath.io`

2024-03-08 13:27 UTC, paulsavoie requested changes
All good, changed some README and action.yml descriptions.

However, update of tests is missing

2024-03-09 10:19 UTC, volbobvol commented
> All good, changed some README and action.yml descriptions.
> 
> However, update of tests is missing



> All good, changed some README and action.yml descriptions.
> 
> However, update of tests is missing

Added unit tests for ExtendedVerificationToken passing through

2024-03-11 06:56 UTC, paulsavoie approved these changes

2024-03-11 07:02 UTC, paulsavoie approved these changes

2024-03-11 08:09 UTC, merged